export const gridItems = [
  {
    id: 1,
    title: "Data Collection",
    description: "Collect physical world data through IoT devices and sensors",
    className: "lg:col-span-3 md:col-span-6 md:row-span-4 lg:min-h-[60vh]",
    img: "",
    imgClassName: "",
    titleClassName: "justify-end",
    spareImg: "",
  },
  {
    id: 2,
    title: "Verification",
    description: "Verify data authenticity using cryptographic proofs",
    className: "lg:col-span-2 md:col-span-3 md:row-span-1",
    img: "",
    imgClassName: "",
    titleClassName: "justify-center",
    spareImg: "",
  },
  {
    id: 3,
    title: "Features",
    description: "Reliable, Fast, Transparent, Secure, Effective, Efficient",
    className: "lg:col-span-2 md:col-span-3 md:row-span-2",
    img: "",
    imgClassName: "",
    titleClassName: "justify-start",
    spareImg: "",
  },
  {
    id: 4,
    title: "On-Chain Storage",
    description: "Store verified data on blockchain for transparency",
    className: "lg:col-span-2 md:col-span-3 md:row-span-1",
    img: "",
    imgClassName: "",
    titleClassName: "justify-center",
    spareImg: "",
  },
  {
    id: 5,
    title: "Access Control",
    description: "Manage who can access your data",
    className: "md:col-span-3 md:row-span-2",
    img: "",
    imgClassName: "",
    titleClassName: "justify-end",
    spareImg: "",
  },
  {
    id: 6,
    title: "Get Started",
    description: "Connect your wallet to begin using the protocol",
    className: "lg:col-span-2 md:col-span-3 md:row-span-1 lg:min-h-[70px]",
    img: "",
    imgClassName: "",
    titleClassName: "justify-center",
    spareImg: "",
  },
];

